global using MassTransit;
global using MassTransit.EntityFrameworkCoreIntegration;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.EntityFrameworkCore.Metadata.Internal;
global using Orchestration.StateMachineWorkerService;
global using Orchestration.StateMachineWorkerService.State;
global using System.ComponentModel.DataAnnotations.Schema;
global using System.Text;
