global using Choreography.StockService.API.Consumers;
global using Choreography.StockService.API.Infrastructure.Context;
global using Choreography.StockService.API.Infrastructure.Entities;
global using MassTransit;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Shared.Choreography;
global using System.Reflection;
